//
// Created by Siebe Mees on 11/12/2023.
//

#ifndef MB_TOG_PROGRAMMING_LANGUAGE_EXECUTOR_H
#define MB_TOG_PROGRAMMING_LANGUAGE_EXECUTOR_H


class Executor {

};


#endif //MB_TOG_PROGRAMMING_LANGUAGE_EXECUTOR_H
