version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:22.04

    environment:
      CMAKE_VERSION: "3.24.0"
      GPP_VERSION: "11.3.0"
      CLANG_VERSION: "14.0.0"
    steps:
      - checkout
      - run: apt update
      - run: sudo apt-get install cmake
      - run: mkdir -p build
      - run: cd build && cmake ..
      - run: cd build && make
