version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:22.04

    environment:
      CMAKE_VERSION: "3.22.1"
      GPP_VERSION: "11.4.0"
      CLANG_VERSION: "14.0.0"
    steps:
      # Building
      - checkout
      - run: apt update
      - run: apt install -y cmake g++
      # Install dependencies
      - run: apt install -y git
      - run: git submodule update --init --recursive
      - run: mkdir -p build
      - run: cd build && cmake .. && make all
      # Testing
      - run: ./tst/OurLang_tst --gtest_output="xml:./test-results/out.xml"
      - store_test_results:
          path: ./test-results/out.xml